import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const grotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog Web Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={grotesk.className}>
        <nav className="bg-gray-800 text-white p-4 flex gap-4">
          <Link href="/" className="hover:underline">
            Home
          </Link>
          <Link href="/blog/create" className="hover:underline">
            Create
          </Link>
          <Link href="/about" className="hover:underline">
            About
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
